### ISSUE TITLE
Log software licensing emails

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-message#49]
Just another popular extension which sends emails that could easily, optionally be logged like FES' are now.

**Comment by pippinsplugins** [comment]
@brashrebel could you elaborate on this? I'm not quite sure what you mean.

**Comment by brashrebel** [comment]
Haha. I guess I need to get better about explaining issues on repos like this now that we're collaborating.

EDD Message has an email logging feature built in.
![Screen Shot 2017-04-20 at 11.18.24 AM](http://static.gitscout.com/8db52c57d94333d6413d807afb6e9e7a411692f8ea251744d8ac678bb104a90c.png)

This allows users to optionally log different types of messages so they can see what was sent, when, to whom, etc. It's been pretty helpful and users have appreciated it. Basically I'm looking to expand this feature set so there are more checkboxes in that group. Especially for other popular extensions which send emails.
![Screen Shot 2017-04-20 at 11.21.02 AM](http://static.gitscout.com/072934dac91632174b7967290998208e63a09b4cd57eef3e7c4037e331ff553c.png)

**Comment by pippinsplugins** [comment]
That's awesome, I didn't realize that was there!
