### ISSUE TITLE
Toggles conflict with Clicky plugin

### ISSUE THREAD

**Issue by brashrebel** [easydigitaldownloads/edd-message#51]
https://secure.helpscout.net/conversation/382656528/61271/?folderId=180499

https://wordpress.org/plugins/clicky/

**Comment by pippinsplugins** [comment]
@brashrebel PR is merged, is the issue fixed?

**Comment by brashrebel** [comment]
@pippinsplugins yep!

**Comment by pippinsplugins** [comment]
@brashrebel let's go ahead and get the update deployed then :+1:
