### ISSUE TITLE
Display and allow exporting of logged Messages (emails)

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-message#75]
EDD Messages has the ability to log emails that are sent via the `EDD_Emails` class. We need to be able to expose these logs to a customer requesting data for an email address.

**Comment by SDavisMedia** [comment]
Looking good over here on the export. 👌 

![e574c30b39a22e94348cc1a882ce49db _image 2018-05-16 at 12 38 49 pm](https://user-images.githubusercontent.com/2359131/40139917-39f9105a-5906-11e8-93d3-78b11f06fb7d.png)

**Comment by SDavisMedia** [comment]
Also sent messages to a customer's secondary email address to see if the exporter properly picked it up and reflected the correct info. All goody. 👌
